## Homework 1 ML Zoomcamp 2026

In [1]:
import numpy as np
import pandas as pd

## Q1. Pandas version

In [2]:
pd.__version__

'3.0.6'

## Getting the data

In [3]:
wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

SyntaxError: invalid syntax (2093024806.py, line 1)

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [5]:
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [6]:
df.count()

model_year             10000
origin                 10000
fuel_type              10000
drivetrain             10000
num_doors              10000
engine_displacement    10000
num_cylinders          10000
horsepower              9123
vehicle_weight         10000
acceleration            9736
fuel_efficiency_mpg    10000
dtype: int64

In [7]:
len(df)

10000

In [8]:
df['fuel_type'].nunique()

3

In [9]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [10]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [11]:
df['horsepower'].describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [12]:
df['horsepower'].median()

np.float64(254.0)

In [13]:
df['horsepower'].nunique()

153

In [14]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [15]:
df['horsepower'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: horsepower, Length: 10000, dtype: bool

In [16]:
df['horsepower'][df['horsepower'].isnull()]

10     NaN
12     NaN
32     NaN
39     NaN
46     NaN
        ..
9955   NaN
9957   NaN
9963   NaN
9980   NaN
9986   NaN
Name: horsepower, Length: 877, dtype: float64

In [17]:
df['horsepower'].fillna(df['horsepower'].mode())

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [18]:
df['horsepower'][df['horsepower'].isnull()]

10     NaN
12     NaN
32     NaN
39     NaN
46     NaN
        ..
9955   NaN
9957   NaN
9963   NaN
9980   NaN
9986   NaN
Name: horsepower, Length: 877, dtype: float64

In [19]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

In [20]:
df['horsepower']

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [21]:
df['horsepower'].isnull().sum()

np.int64(877)

In [22]:
df['horsepower'][df['horsepower'].isnull()]

10     NaN
12     NaN
32     NaN
39     NaN
46     NaN
        ..
9955   NaN
9957   NaN
9963   NaN
9980   NaN
9986   NaN
Name: horsepower, Length: 877, dtype: float64

In [23]:
df['horsepower'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: horsepower, Length: 10000, dtype: bool

In [24]:
df['horsepower'][10]

np.float64(nan)

In [25]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [26]:
df['horsepower'].fillna(df['horsepower'].mode()).median()

np.float64(254.0)

In [27]:
df['horsepower'].median()

np.float64(254.0)

In [28]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [29]:
df.groupby('origin').horsepower.mean()

origin
Asia      247.662514
Europe    248.814135
USA       263.038612
Name: horsepower, dtype: float64

In [30]:
df_asia = df[
    df['origin'] == 'Asia'
]

In [31]:
len(df_asia)

2994

In [32]:
df_asia[['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

## Select the 7 first cars made in Asia

In [33]:
df_asia[['vehicle_weight', 'model_year']].head(n=7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [34]:
df_asia7 = df_asia[['vehicle_weight', 'model_year']].head(n=7)

In [35]:
df_asia7

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

## Get the numpy Array

In [50]:
X = np.array(df_asia7)

In [37]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

## Compute Matrix-Matrix multiplication between X_trans and X
- Invert XTX.
- Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
- Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
- What's the sum of all the elements of the result?

In [38]:
X_trans = np.transpose(X)

In [39]:
XTX = X_trans.dot(X)

In [40]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [41]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [42]:
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [43]:
XTX_inv = np.linalg.inv(XTX)

In [44]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [52]:
W = XTX_inv.dot(X_trans).dot(y)

In [53]:
W

array([0.13644777, 0.2327492 ])

## Sum of all results

In [59]:
W.sum()

np.float64(0.36919696904925486)